In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("C:\\Users\\Harsh darji\\.config\\Downloads\\tested.csv") #"C:\Users\Harsh darji\.config\Downloads\tested.csv"

In [8]:
print(df)

     PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]

In [50]:
df.head() #with use of head u can see starting of data

,PassengerId,Survived,Pclass,food,Name,Sex,Equiments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,XYZ
0,892,0,3,0,"Kelly, Mr. James",male,Oxygen cylinder,34.5,0,0,330911,7.8292,NaN,Q,2.5,2.5
1,893,1,3,0,"Wilkes, Mrs. James (Ellen Needs)",female,Oxygen cylinder,47.0,1,0,363272,7.0000,NaN,S,2.5,2.5
2,894,0,2,0,"Myles, Mr. Thomas Francis",male,Oxygen cylinder,62.0,0,0,240276,9.6875,NaN,Q,2.5,2.5
3,895,0,3,0,"Wirz, Mr. Albert",male,Oxygen cylinder,27.0,0,0,315154,8.6625,NaN,S,2.5,2.5
4,896,1,3,0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,Oxygen cylinder,22.0,1,1,3101298,12.2875,NaN,S,2.5,2.5

In [51]:
df.tail() #with use of tail u can see last data with parametrer

,PassengerId,Survived,Pclass,food,Name,Sex,Equiments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,XYZ
413,1305,0,3,0,"Spector, Mr. Woolf",male,Oxygen cylinder,NaN,0,0,A.5. 3236,8.0500,NaN,S,2.5,2.5
414,1306,1,1,0,"Oliva y Ocana, Dona. Fermina",female,Oxygen cylinder,39.0,0,0,PC 17758,108.9000,C105,C,2.5,2.5
415,1307,0,3,0,"Saether, Mr. Simon Sivertsen",male,Oxygen cylinder,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,2.5,2.5
416,1308,0,3,0,"Ware, Mr. Frederick",male,Oxygen cylinder,NaN,0,0,359309,8.0500,NaN,S,2.5,2.5
417,1309,0,3,0,"Peter, Master. Michael J",male,Oxygen cylinder,NaN,1,1,2668,22.3583,NaN,C,2.5,2.5

In [11]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [12]:
df.dtypes #with use of dtype u van show data type

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [13]:
df.describe()  #numerical data

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [14]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [16]:
df[['Name','Sex','Ticket','Cabin','Embarked']]  #with the use of u can select any column

,Name,Sex,Ticket,Cabin,Embarked
0,"Kelly, Mr. James",male,330911,NaN,Q
1,"Wilkes, Mrs. James (Ellen Needs)",female,363272,NaN,S
2,"Myles, Mr. Thomas Francis",male,240276,NaN,Q
3,"Wirz, Mr. Albert",male,315154,NaN,S
4,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,3101298,NaN,S
...,...,...,...,...,...
413,"Spector, Mr. Woolf",male,A.5. 3236,NaN,S
414,"Oliva y Ocana, Dona. Fermina",female,PC 17758,C105,C
415,"Saether, Mr. Simon Sivertsen",male,SOTON/O.Q. 3101262,NaN,S
416,"Ware, Mr. Frederick",male,359309,NaN,S
417,"Peter, Master. Michael J",male,2668,NaN,C

In [17]:
df.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [19]:
df.dtypes == 'float64'  # with use of u can shoe float

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare            True
Cabin          False
Embarked       False
dtype: bool

In [20]:
df[df.dtypes[df.dtypes == 'float64'].index] # with use of u can see float64 data types

      Age      Fare
0    34.5    7.8292
1    47.0    7.0000
2    62.0    9.6875
3    27.0    8.6625
4    22.0   12.2875
..    ...       ...
413   NaN    8.0500
414  39.0  108.9000
415  38.5    7.2500
416   NaN    8.0500
417   NaN   22.3583

[418 rows x 2 columns]

In [21]:
df[df.dtypes[df.dtypes == 'int64'].index] # with use of u can see int64 data types

     PassengerId  Survived  Pclass  SibSp  Parch
0            892         0       3      0      0
1            893         1       3      1      0
2            894         0       2      0      0
3            895         0       3      0      0
4            896         1       3      1      1
..           ...       ...     ...    ...    ...
413         1305         0       3      0      0
414         1306         1       1      0      0
415         1307         0       3      0      0
416         1308         0       3      0      0
417         1309         0       3      1      1

[418 rows x 5 columns]

In [22]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [23]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [24]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
408,1300,1,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
410,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [25]:
df.columns # with use of this u can see columns name

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [26]:
df[['Ticket']]

                 Ticket
0                330911
1                363272
2                240276
3                315154
4               3101298
..                  ...
413           A.5. 3236
414            PC 17758
415  SOTON/O.Q. 3101262
416              359309
417                2668

[418 rows x 1 columns]

In [28]:
df[['Ticket']][4:16] #slicing

           Ticket
4         3101298
5            7538
6          330972
7          248738
8            2657
9       A/4 48871
10         349220
11            694
12          21228
13          24065
14    W.E.P. 5734
15  SC/PARIS 2167

In [29]:
df[['Ticket']][4:16:2] #jump 2 for 1 value drop

         Ticket
4       3101298
6        330972
8          2657
10       349220
12        21228
14  W.E.P. 5734

In [31]:
df[['Ticket','Cabin']]

                 Ticket Cabin
0                330911   NaN
1                363272   NaN
2                240276   NaN
3                315154   NaN
4               3101298   NaN
..                  ...   ...
413           A.5. 3236   NaN
414            PC 17758  C105
415  SOTON/O.Q. 3101262   NaN
416              359309   NaN
417                2668   NaN

[418 rows x 2 columns]

In [32]:
df[['Ticket','Cabin']][4:17] #slicing

           Ticket Cabin
4         3101298   NaN
5            7538   NaN
6          330972   NaN
7          248738   NaN
8            2657   NaN
9       A/4 48871   NaN
10         349220   NaN
11            694   NaN
12          21228   B45
13          24065   NaN
14    W.E.P. 5734   E31
15  SC/PARIS 2167   NaN
16         233734   NaN

In [33]:
df[['Ticket','Cabin']][4:17:3] #jump of 2

     Ticket Cabin
4   3101298   NaN
7    248738   NaN
10   349220   NaN
13    24065   NaN
16   233734   NaN

In [34]:
df[['Name','Ticket','Cabin']][4:17:3]

                                            Name   Ticket Cabin
4   Hirvonen, Mrs. Alexander (Helga E Lindqvist)  3101298   NaN
7                   Caldwell, Mr. Albert Francis   248738   NaN
10                              Ilieff, Mr. Ylio   349220   NaN
13                          Howard, Mr. Benjamin    24065   NaN
16                             Keane, Mr. Daniel   233734   NaN

In [35]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [36]:
#how to create a new column and value show 0

In [43]:
df['XYZ'] = 2.5

In [44]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,XYZ
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,2.5,2.5
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,2.5,2.5
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,2.5,2.5
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,2.5,2.5
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2.5,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,2.5,2.5
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,2.5,2.5
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,2.5,2.5
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,2.5,2.5
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2.5,2.5

In [45]:
#set a location of column

In [46]:
df.insert(loc = 3 , column = 'food' , value = 0)

In [47]:
df

,PassengerId,Survived,Pclass,food,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,XYZ
0,892,0,3,0,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,2.5,2.5
1,893,1,3,0,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,2.5,2.5
2,894,0,2,0,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,2.5,2.5
3,895,0,3,0,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,2.5,2.5
4,896,1,3,0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,2.5,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,2.5,2.5
414,1306,1,1,0,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,2.5,2.5
415,1307,0,3,0,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,2.5,2.5
416,1308,0,3,0,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,2.5,2.5
417,1309,0,3,0,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,2.5,2.5

In [48]:
df.insert(loc = 6 , column = 'Equiments' , value = 'Oxygen cylinder')

In [49]:
df

,PassengerId,Survived,Pclass,food,Name,Sex,Equiments,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,XYZ
0,892,0,3,0,"Kelly, Mr. James",male,Oxygen cylinder,34.5,0,0,330911,7.8292,NaN,Q,2.5,2.5
1,893,1,3,0,"Wilkes, Mrs. James (Ellen Needs)",female,Oxygen cylinder,47.0,1,0,363272,7.0000,NaN,S,2.5,2.5
2,894,0,2,0,"Myles, Mr. Thomas Francis",male,Oxygen cylinder,62.0,0,0,240276,9.6875,NaN,Q,2.5,2.5
3,895,0,3,0,"Wirz, Mr. Albert",male,Oxygen cylinder,27.0,0,0,315154,8.6625,NaN,S,2.5,2.5
4,896,1,3,0,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,Oxygen cylinder,22.0,1,1,3101298,12.2875,NaN,S,2.5,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,"Spector, Mr. Woolf",male,Oxygen cylinder,NaN,0,0,A.5. 3236,8.0500,NaN,S,2.5,2.5
414,1306,1,1,0,"Oliva y Ocana, Dona. Fermina",female,Oxygen cylinder,39.0,0,0,PC 17758,108.9000,C105,C,2.5,2.5
415,1307,0,3,0,"Saether, Mr. Simon Sivertsen",male,Oxygen cylinder,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,2.5,2.5
416,1308,0,3,0,"Ware, Mr. Frederick",male,Oxygen cylinder,NaN,0,0,359309,8.0500,NaN,S,2.5,2.5
417,1309,0,3,0,"Peter, Master. Michael J",male,Oxygen cylinder,NaN,1,1,2668,22.3583,NaN,C,2.5,2.5